[tool.poetry]
name = "hw"
version = "0.1.0"
description = ""
authors = ["frederikibara"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
